# Generated by Django 5.1.3 on 2024-11-27 20:55

import otp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Keys",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome_servico",
                    models.CharField(max_length=100, verbose_name="Nome do Serviço"),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Chave secreta de 32 caracteres",
                        max_length=32,
                        validators=[otp.models.validate_base32_key],
                        verbose_name="Chave TOTP",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chave TOTP",
                "verbose_name_plural": "Chaves TOTP",
                "ordering": ["nome_servico"],
            },
        ),
    ]
