# Generated by Django 6.0 on 2025-12-04 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Keys",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome_servico",
                    models.CharField(max_length=100, verbose_name="Nome do Serviço"),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Chave secreta de 32 caracteres",
                        max_length=255,
                        verbose_name="Chave TOTP",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data da última alteração"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chave TOTP",
                "verbose_name_plural": "Chaves TOTP",
                "ordering": ["nome_servico"],
            },
        ),
    ]
