# Generated by Django 5.1.3 on 2024-11-27 21:10

import otp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keys",
            name="key",
            field=models.CharField(
                help_text="Chave secreta de 32 caracteres",
                max_length=100,
                validators=[otp.models.validate_base32_key],
                verbose_name="Chave TOTP",
            ),
        ),
    ]
